"""changing DbVote from created_at to voted_at

Revision ID: 19b2a6457847
Revises: 
Create Date: 2025-09-21 13:28:49.345249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b2a6457847'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.add_column('votes', sa.Column('voted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('votes', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_column('votes', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.alter_column('votes', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('votes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('votes', 'voted_at')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.alter_column('articles', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
